apiVersion: v1
kind: Namespace
metadata:
  name: appflask
  labels:
    name: appflask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflask-deployment
  namespace: appflask
  labels:
    app: appflask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appflask
  template:
    metadata:
      labels:
        app: appflask
    spec:
      containers:
      - name: appflask
        image: deepthikonka/sample_flask:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: appflask
  namespace: appflask
spec:
  selector:
    app: appflask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer